### ISSUE TITLE
CSV with single cell rows not ending with CRLF not supported

### ISSUE THREAD

**Issue by gmichaudAniki** [yutokun/CSV-Parser#8]
When trying to parse CSV data looking like this :

`Action\r\nAdventure\r\nThriller`

The last row "Thriller" is ignored. 
To circumvent this issue I am checking the content of the cell in addition to the row in CSVParser.cs line 155 :
`if (row.Count > 0 || cell.Length > 0)`

Also, thank you for this amazing tool !

**Comment by yutokun** [comment]
Thank you so much about your report and fix! I added tests to ensure improved parser correctly work.

By the way, I noticed .NET 5 is [no longer supported](https://github.com/dotnet/core/blob/main/os-lifecycle-policy.md) and can't use on CI. I'm upgrading projects to .NET 6 and will check usable environments. After that, I'm going to release new version based on your report.

**Comment by yutokun** [comment]
@gmichaudAniki I have published a fixed version. Thank you for your report! If you notice any issues, feel free to reopen.

https://github.com/yutokun/CSV-Parser/releases/tag/v2.0.1
